version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: faceid-backend
    ports:
      - "3000:3000"
    environment:
      - GIN_MODE=debug
    networks:
      - faceid-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: faceid-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - faceid-network
    restart: unless-stopped

networks:
  faceid-network:
    driver: bridge 